AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: The git repository
      RepositoryName:  orestis-test-repo
  CodeBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
       Fn::Join:
       - ''
       - - Ref: AWS::Region
         - 'CustomCodeBuildRole'


  CodeBuilder:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        EncryptionDisabled: true
        Name: test-repo-build
        Type: S3
        Location: orestis
        Packaging: ZIP
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/java:openjdk-8
          Type: LINUX_CONTAINER
        ServiceRole:










