AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Dynamic Pipelines

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  Branch:
    Type: String
  LambdaTrustRoleArn:
    Type: String
  CodeBucket:
    Type: String

Resources:

  RestApi:
    DependsOn:
      - BuildBranch
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        openapi: 3.0.0
        info:
          title: A titleless API
          description: Small api to build a branch
          version: "0.1"
        paths:
          /buildbranch:
            post:
              operationId: insertEntry
              responses: {}
              requestBody:
                content:
                  application/json :
                    schema:
                      properties:
                        repositoryName:
                          description: The name of the repository
                          type: string
                        branch:
                          description: The name of the branch
                          type: string
                        owner:
                          description: The owner
                          type: string
                        action:
                          description: create or update
                          type: string
                    example:
                      repositoryName: 'authority-registry'
                      branch: master
                      owner: BIBSYSDEV
                      action: create
              x-amazon-apigateway-integration:
#                uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:933878624978:function:aut-reg-inf-master-serviceStack-prod-BuildBranch-Q0C8OEDSI0N5/invocations"
                uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BuildBranch.Arn}/invocations'
                httpMethod: "POST"
                type: aws_proxy
                passthroughBehavior: when_no_match

  GithubHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !Ref LambdaTrustRoleArn
      MemorySize:  1500
      Timeout: 900
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /github
            Method: post
            RestApiId: !Ref RestApi
  BuildBranch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.CustomBranchBuilder::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !Ref LambdaTrustRoleArn
      MemorySize:  1500
      Timeout: 900
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /buildbranch
            Method: post
            RestApiId: !Ref RestApi
