AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Dynamic Pipelines

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  Branch:
    Type: String
  LambdaTrustRoleArn:
    Type: String
  CodeBucket:
    Type: String

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  GithubHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !Ref LambdaTrustRoleArn
      MemorySize:  1500
      Timeout: 900
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /github
            Method: post
            RestApiId: !Ref RestApi
  BuildBranch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.CustomBranchBuilder::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !Ref LambdaTrustRoleArn
      MemorySize:  1500
      Timeout: 900
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /buildbranch
            Method: post
            RestApiId: !Ref RestApi

  RestApiUrlParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Join ['-', [!Ref ProjectId, !Ref Branch, "restApiUrlParameter"]]
      Type: "String"
      Value: !Join ['', ['https://', !Ref 'RestApi', '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/',!Ref Stage]]
      Description: "SSM Parameter for storing RestApi URL"