AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Dynamic Pipelines

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  LambdaTrustRolename:
    Type: String


Resources:
  LambdaTrustRole:
    Type: 'AWS::IAM::Role'
    Description: A trust role that will be assumed by the service
    Properties:
      RoleName: !Ref LambdaTrustRolename
      AssumeRolePolicyDocument:
        Statement:
        - Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
           Service:
            - lambda.amazonaws.com
            - cloudformation.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole'
      Path: /
      Policies:
        -
          PolicyName: ReadSecrets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Resource: '*'
                Action:
                  - 'secretsmanager:GetSecretValue '
        -
          PolicyName: LambdaWorkerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Effect: Allow
                  Resource: '*'
                  Action:
                    - "ssm:GetParameter"
        -
          PolicyName: StackPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            -
              Effect: Allow
              Resource: '*'
              Action:
              - "ssm:GetParameter"
        - PolicyName: "passRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Action:
              - 'iam:PassRole'
              Effect: Allow
              Resource: "*"
            -
              Action:
                - 'cloudformation:CreateChangeSet'
              Effect: Allow
              Resource:
              - arn:aws:cloudformation:eu-west-1:aws:transform/Serverless-2016-10-31
          -
            Action:
            - 'iam:GetRole'
            - 'iam:CreateRole'
            - 'iam:PutRolePolicy'
            - 'iam:DetachRolePolicy'
            - 'iam:DeleteRolePolicy'
            - 'iam:DeleteRole'
            - 'iam:AttachRolePolicy'
            - 'ssm:PutParameter'
            - 'ssm:DeleteParameter'
            Resource: '*'
            Effect: Allow
        -
          PolicyName: createLambdaFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            -
              Effect: Allow
              Action:
                - 'lambda:CreateFunction'
                - 'lambda:DeleteFunction'
                - 'lambda:AddPermission'
                - 'lambda:UpdateFunction'
                - 'lambda:UpdateFunctionCode'
                - 'lambda:GetFunction'
                - 'lambda:GetFunctionConfiguration'
                - 'lambda:UpdateFunctionConfiguration'
                - 'lambda:RemovePermission'
                - 'lambda:listTags'
                - 'lambda:TagResource'
                - 'lambda:UntagResource'
                - 'apigateway:*'
                - 'ssm:GetParameters'
            Resource: '*'

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  EntityRegistry:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !GetAtt LambdaTrustRole.Arn
      MemorySize:  1500
      Timeout: 900
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /lambda
            Method: post
            RestApiId: !Ref RestApi

  RestApiUrlParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Join ['-', [!Ref ProjectId,"restApiUrlParameter"]]
      Type: "String"
      Value: !Join ['', ['https://', !Ref 'RestApi', '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/',!Ref Stage]]
      Description: "SSM Parameter for storing RestApi URL"