AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Dynamic Pipelines


Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  EntityRegistry:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
#      Role: !Ref TrustRoleArn
      Timeout: 60
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: "/lambda"
            Method: post
