AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Dynamic Pipelines


Resources:
  LambdaTrustRole:
    Type: 'AWS::IAM::Role'
    Description: A trust role that will be assumed by the service
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
           Service:
            - lambda.amazonaws.com
            - cloudformation.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole'
      Path: /
      Policies:
        -
          PolicyName: lambdaPolicy
          Version: 2012-10-17
          PolicyDocument:
            Statement:
               -
                  Effect: Allow
                  Resource: '*'
                  Action:
                    - "ssm:GetParameter"



  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  EntityRegistry:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handler.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/pipeline-fat.jar
      Role: !GetAtt LambdaTrustRole.Arn
      Timeout: 60
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: "/lambda"
            Method: get
