AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Building a pipeline
Parameters:
  ProjectId:
    Type: String
  ProjectBranch:
    Type: String
  GithubAuth:
    Type: String
  GithubOwner:
    Type: String
  GithubRepo:
    Type: String
  PipelineBucketname:
    Type: String
  PipelineRolename:
    Type: String
  CreateStackRolename:
    Type: String
  PipelineName:
    Type: String
  CodebuildProjectname:
    Type: String
  CodebuildOutputArtifact:
    Type: String
  SourceStageOutputArtifact:
    Type: String
  TestStackName:
    Type: String


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Ref PipelineBucketname
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms

  CreateStackRole:
    DependsOn:
    - PipelineRole
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CreateStackRolename
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: 1
          Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - cloudformation.amazonaws.com
            - codepipeline.amazonaws.com
            - codebuild.amazonaws.com
            - iam.amazonaws.com
            AWS: !GetAtt PipelineRole.Arn

      Policies:
      - PolicyName: "passRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - 'iam:PassRole'
            Effect: Allow
            Resource: "*"
          - Action:
            - 'cloudformation:CreateChangeSet'
            Effect: Allow
            Resource:
            - arn:aws:cloudformation:eu-west-1:aws:transform/Serverless-2016-10-31
      -
        PolicyName: s3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
              Resource:
                - !Join ["", [!GetAtt S3Bucket.Arn, "/*"]]
                - !GetAtt S3Bucket.Arn

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref PipelineRolename
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - lambda.amazonaws.com
            - codepipeline.amazonaws.com
            - codebuild.amazonaws.com
            - cloudformation.amazonaws.com
            - iam.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess

      Policies:
      - PolicyName: s3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - !Join ["", [!GetAtt S3Bucket.Arn, "/*"]]
            - !GetAtt S3Bucket.Arn
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
      - PolicyName: cloudFormationAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudformation:DescribeStacks
            - cloudformation:DescribeChangeSet
            - cloudformation:CreateChangeSet
            - cloudformation:DeleteChangeSet
            - cloudformation:ExecuteChangeSet
            Resource:
            - !Sub
              - 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${StackName}/*'
              -  { StackName: !Ref TestStackName }
      - PolicyName: assumeRole
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - 'sts:AssumeRole'
            Effect: Allow
            Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Description: CodeBuild project for using in the CodePipeline
    Properties:
      Name: !Ref CodebuildProjectname
      Artifacts:
        Name: !Ref CodebuildOutputArtifact
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/eb-java-8-amazonlinux-64:2.4.3"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: S3_BUCKET
          Type: PLAINTEXT
          Value: !Ref PipelineBucketname
      ServiceRole: !GetAtt PipelineRole.Arn

  Pipeline:
    DependsOn:
    - CodeBuildProject
    - CreateStackRole
    - PipelineRole
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      Name: !Ref PipelineName
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucketname
      Stages:
      - Name: Github_pull
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Provider: GitHub
            Owner: ThirdParty
            Version: 1
          Configuration:
            Owner: !Ref GithubOwner
            Repo:   !Ref GithubRepo
            OAuthToken: !Ref GithubAuth
            Branch: !Ref ProjectBranch
          OutputArtifacts:
          - Name: !Ref SourceStageOutputArtifact
      - Name: CodeBuild
        Actions:
        -
          Name: CodeBuildAction
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: 1
          InputArtifacts:
          - Name: !Ref SourceStageOutputArtifact
          OutputArtifacts:
          - Name: !Ref CodebuildOutputArtifact
          Configuration:
            ProjectName: !Ref CodebuildProjectname

      - Name: TestStack
        Actions:
        - Name: CreateTestStack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CloudFormation
          Configuration:
            ActionMode: CHANGE_SET_REPLACE
            StackName: !Ref TestStackName
            ChangeSetName: TestStageChangeSet
            Capabilities: CAPABILITY_IAM
            RoleArn: !GetAtt CreateStackRole.Arn
            TemplatePath: !Join ["", [!Ref CodebuildOutputArtifact,"::template-export.yml"]]
            ParameterOverrides:
               !Sub
                - '{"ProjectId":"${ProjectIdValue}", "Stage":"${StageValue}"}'
                - { ProjectIdValue: !Ref ProjectId, StageValue: !Ref ProjectBranch }

          InputArtifacts:
          - Name: !Ref CodebuildOutputArtifact
          RunOrder: 1
        -
          Name: ExecuteTestStack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: test-stack-execute
            StackName: !Ref TestStackName
          InputArtifacts: []
          OutputArtifacts: []
          RunOrder: 2
        -
          Name: ManualReview
          ActionTypeId:
            Category: Approval # TODO: automated function tests
            Owner: AWS
            Provider: Manual
            Version: 1
          RunOrder: 3
        -
          Name: DeleteTestStack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          Configuration:
            ActionMode: DELETE_ONLY
            RoleArn: !GetAtt CreateStackRole.Arn
            StackName: !Ref TestStackName
          RunOrder: 4
