AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Building a pipeline"
Parameters:
  ProjectName:
    Type: String
    DefaultValue: UnknownProject
  Branch:
    Type: String
    DefaultValue: UknownBranch
  PipelineRoleName:
    Type: String
    MinLength: 1
    MaxLength: 100

Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
        - sts:AssumeRole
        Principal:
          Service:
          - lambda.amazonaws.com
          - codepipeline.amazonaws.com
          - codebuild.amazonaws.com
          - cloudformation.amazonaws.com
          - iam.amazonaws.com
    ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSCodePipelineFullAccess"
      -  "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
      - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
